package uuid_test

import (
	"testing"
	"time"

	"gosuda.org/uuid"
)

func TestNewV7(t *testing.T) {
	id := uuid.NewV7()
	if len(id) != 16 {
		t.Errorf("NewV7() returned UUID with length %d, want 16", len(id))
	}
}

func TestUUIDV7Version(t *testing.T) {
	uuid := uuid.NewV7()
	if (uuid[6] & 0xf0) != 0x70 {
		t.Errorf("UUID version is not 7, got 0x%x", uuid[6])
	}
}

func TestUUIDV7Variant(t *testing.T) {
	uuid := uuid.NewV7()
	if (uuid[8] & 0x80) != 0x80 {
		t.Errorf("UUID variant is not IETF variant DCE 1.1, got 0x%x", uuid[8])
	}
}

func TestUUIDUniqueness(t *testing.T) {
	uuid1 := uuid.NewV7()
	time.Sleep(1 * time.Nanosecond)
	uuid2 := uuid.NewV7()
	if uuid1 == uuid2 {
		t.Errorf("UUIDs generated by NewV7() are not unique")
	}
}

func BenchmarkNewV7(b *testing.B) {
	for i := 0; i < b.N; i++ {
		uuid.NewV7()
	}
}

func BenchmarkConcurrencyNewV7(b *testing.B) {
	b.SetParallelism(100_000)
	b.RunParallel(func(p *testing.PB) {
		for p.Next() {
			uuid.NewV7()
		}
	})
}
